<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/lbrc-devel/2008-January/index.html" >
   <LINK REL="made" HREF="mailto:lbrc-devel%40lists.berlios.de?Subject=Re%3A%20%5BLbrc-devel%5D%20DBUS%20Daemon%20not%20running%20%28was%3A%20Re%3A%20LBRC%20errors%29&In-Reply-To=%3CPine.LNX.4.64.0801111241230.24572%40poblijon.ubal.to%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000058.html">
   <LINK REL="Next"  HREF="000060.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)</H1>
    <B>tloudev</B> 
    <A HREF="mailto:lbrc-devel%40lists.berlios.de?Subject=Re%3A%20%5BLbrc-devel%5D%20DBUS%20Daemon%20not%20running%20%28was%3A%20Re%3A%20LBRC%20errors%29&In-Reply-To=%3CPine.LNX.4.64.0801111241230.24572%40poblijon.ubal.to%3E"
       TITLE="[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)">k at mo.ubal.to
       </A><BR>
    <I>Fri Jan 11 13:09:51 CET 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="000058.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
        <LI>Next message: <A HREF="000060.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59">[ date ]</a>
              <a href="thread.html#59">[ thread ]</a>
              <a href="subject.html#59">[ subject ]</a>
              <a href="author.html#59">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>hi Matthias,
so the correct version of the dbus-python should be &gt;=0.80.. OK.
right now it seems much better in this case, but I have another error, 
probably between the chair and the keyboard again :-)

    O.P.

kino lbrc-0.5 # cat .lbrc.conf
{
     &quot;uinputdevice&quot;: &quot;/dev/misc/uinput&quot;,
     &quot;defaultprofile&quot;: &quot;nokia_6230i_maus1&quot;
}
kino lbrc-0.5 # LBRCdbus --debug
Traceback (most recent call last):
   File &quot;/usr/bin/LBRCdbus&quot;, line 13, in &lt;module&gt;
     brs = Core(debug=logging.DEBUG)
   File &quot;/usr/lib/python2.5/site-packages/LBRC/dbusinterface.py&quot;, line 204, 
in __init__
     self.btserver = BTServer()
   File &quot;/usr/lib/python2.5/site-packages/LBRC/BTServer.py&quot;, line 185, in 
__init__
     self.config = config()
   File &quot;/usr/lib/python2.5/site-packages/LBRC/config.py&quot;, line 42, in 
__init__
     self.reread()
   File &quot;/usr/lib/python2.5/site-packages/LBRC/config.py&quot;, line 72, in 
reread
     self.profile_index.extend([('user', profile_name) for profile_name in 
self.user['profiles']])
KeyError: 'profiles'

I'd like to change the profile, but Idon't know where can I find other 
profiles available.
kino lbrc-0.5 # find ./ -name &quot;*nokia*&quot;
./doc/mappings/nokia_6230i.txt
./doc/mappings/nokia_n70.txt
kino lbrc-0.5 # grep -r &quot;nokia&quot; *
config.conf:    &quot;defaultprofile&quot;: &quot;nokia_6230i_maus1&quot;
doc/bluez-dbus-api.txt:Copyright (C) 2005-2006  Johan Hedberg 
&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/lbrc-devel">johan.hedberg at nokia.com</A>&gt;
doc/config.conf:    &quot;defaultprofile&quot;: &quot;nokia_6230i_maus1&quot;


On Fri, 11 Jan 2008, Matthias Bl&#228;sing wrote:
&gt;<i> I will only comment on the problems with the newer bindings (the 0.8
</I>&gt;<i> version, as that is the version also present in debian unstable).
</I>&gt;<i> This looks like you are trying to run LBRC as root. Firstly: I don't
</I>&gt;<i> know why this is so popular, but I would strongly advise against it.
</I>
yes of course... Just a tuning phase to avoid permission problems.

&gt;<i> But the basic problem would stay - namely: There is no dbus daemon
</I>&gt;<i> running. Or at least it can't be accessed. If no dbus daemon is launched
</I>&gt;<i> automaticly - you have to do it yourself (its explained in more detail
</I>&gt;<i> in the manual pages of dbus-launch).
</I>
hmm... interesting.. I start dbus from /etc/init.d at the boot time and 
accd to ps axuw it's running.
101       3582  0.0  0.1   2180   832 ?        Ss   13:28   0:00 
/usr/bin/dbus-daemon --system

&gt;<i> dbus-launch will invoke a new session bus and will print the enviroment
</I>&gt;<i> variables necessary for the programms, that want to use the bus. You
</I>&gt;<i> have to set these variables yourself, as a programm can't modify the
</I>&gt;<i> environment of the calling parent.
</I>&gt;<i> So you can either run dbus-launch and manually export the variables or
</I>&gt;<i> use the shell to help you:
</I>&gt;<i> <A HREF="https://lists.berlios.de/mailman/listinfo/lbrc-devel">test at prometheus</A>:~$ eval `dbus-launch`
</I>&gt;<i> <A HREF="https://lists.berlios.de/mailman/listinfo/lbrc-devel">test at prometheus</A>:~$ export DBUS_SESSION_BUS_ADDRESS
</I>&gt;<i> <A HREF="https://lists.berlios.de/mailman/listinfo/lbrc-devel">test at prometheus</A>:~$ export DBUS_SESSION_BUS_PID
</I>
&gt;&gt;<i> I'm trying to run LBRC v0.5, but I have several problems runnin 
</I>LBRCdbus
&gt;&gt;<i> with dbus-python &gt;=0.80 the proram exits with:
</I>&gt;&gt;<i> kino lbrc-0.5 # LBRCdbus --debug
</I>&gt;&gt;<i> Traceback (most recent call last):
</I>&gt;&gt;<i>    File &quot;/usr/bin/LBRCdbus&quot;, line 13, in &lt;module&gt;
</I>&gt;&gt;<i>      brs = Core(debug=logging.DEBUG)
</I>&gt;&gt;<i>    File &quot;/usr/lib/python2.5/site-packages/LBRC/dbusinterface.py&quot;, line 195,
</I>&gt;&gt;<i> in __init__
</I>&gt;&gt;<i>      bus_name = dbus.service.BusName(DBUSNAME, bus=dbus.SessionBus())
</I>&gt;&gt;<i>    File &quot;/usr/lib/python2.5/site-packages/dbus/_dbus.py&quot;, line 213, in
</I>&gt;&gt;<i> __new__
</I>&gt;&gt;<i>      mainloop=mainloop)
</I>&gt;&gt;<i>    File &quot;/usr/lib/python2.5/site-packages/dbus/_dbus.py&quot;, line 102, in
</I>&gt;&gt;<i> __new__
</I>&gt;&gt;<i>      bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
</I>&gt;&gt;<i>    File &quot;/usr/lib/python2.5/site-packages/dbus/bus.py&quot;, line 125, in
</I>&gt;&gt;<i> __new__
</I>&gt;&gt;<i>      bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
</I>&gt;&gt;<i> dbus.exceptions.DBusException:
</I>&gt;&gt;<i> org.freedesktop.DBus.Error.Spawn.ExecFailed:
</I>&gt;&gt;<i> Failed to execute dbus-launch to autolaunch D-Bus session
</I>


--

Check my PGP public key at <A HREF="http://poblijon.ubal.to/~tloudev/pgp.pub">http://poblijon.ubal.to/~tloudev/pgp.pub</A>


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000058.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
	<LI>Next message: <A HREF="000060.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#59">[ date ]</a>
              <a href="thread.html#59">[ thread ]</a>
              <a href="subject.html#59">[ subject ]</a>
              <a href="author.html#59">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/lbrc-devel">More information about the Lbrc-devel
mailing list</a><br>
</body></html>
